name: Java CI with Manual JUnit and Checkstyle

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download JUnit Console Standalone
        run: |
          wget -O junit-platform-console-standalone.jar https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.10.1/junit-platform-console-standalone-1.10.1.jar

      - name: Compile Java Source Files
        run: |
          mkdir -p out
          find Jabberpoint-IT/app/src/main/java -name "*.java" > sources.txt
          javac -d out @sources.txt

      - name: Compile Java Test Files
        run: |
          find Jabberpoint-IT/app/src/test/java -name "*.java" > test_sources.txt || echo "No test sources"
          if [ -s test_sources.txt ]; then
            javac -cp out:junit-platform-console-standalone.jar -d out @test_sources.txt
          fi

      - name: Run JUnit Tests
        run: |
          mkdir -p test-results
          java -jar junit-platform-console-standalone.jar \
            --class-path out \
            --scan-classpath \
            --details verbose \
            --reports-dir=test-results || echo "No tests found or some failed"

      - name: Upload JUnit Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: test-results

      - name: Download Checkstyle
        run: wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.4/checkstyle-10.12.4-all.jar -O checkstyle.jar

      - name: Run Checkstyle (Readable and XML Output)
        run: |
          # Human-readable warnings in console:
          java -jar checkstyle.jar -c Jabberpoint-IT/app/checkstyle.xml \
            -f plain \
            Jabberpoint-IT/app/src/main/java \
            Jabberpoint-IT/app/src/test/java || echo "Checkstyle violations found"

          # XML output for uploading:
          java -jar checkstyle.jar -c Jabberpoint-IT/app/checkstyle.xml \
            -f xml -o checkstyle-result.xml \
            Jabberpoint-IT/app/src/main/java \
            Jabberpoint-IT/app/src/test/java || echo "Checkstyle XML generation failed"
          
          # Ensure file always exists to prevent upload errors
          [ -f checkstyle-result.xml ] || touch checkstyle-result.xml

      - name: Upload Checkstyle Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: checkstyle-result.xml
